<?php/***************************************************** **作者：张文晓**创始时间：2017-03-03**描述：商户端基础信息service类。*****************************************************/
require_once (dirname(dirname(dirname(__FILE__)))."/libraries/Includes.php");class InformationService{	#.引用属性，每个控制器都需要有	private $includes;	private $data;	private $model;	private $item=13;	private $system;	private $session;
/** *********************************************************** *方法::InformationService::__construct * ---------------------------------------------------------- *描述::商户端基础信息service类初始化方法 *---------------------------------------------------------- *参数: *parm1:in--    无 *---------------------------------------------------------- *返回： *return:out--  无 * ---------------------------------------------------------- * 日期:2017.03.03  Add by zwx ************************************************************ */
public function __construct(){	$this->includes=new Includes(__FILE__);	$this->includes->models("DataBase","global");	$this->includes->models("InformationModel");	$this->includes->libraries("CurrSystem");    $this->includes->libraries("CurrLog");    $this->includes->libraries("CurrSession");    $this->session=new CurrSession();    $this->system=new CurrSystem();	$this->model=new InformationModel();    $this->data=new DataBase();}
/** *********************************************************** *方法::InformationService::getInformation * ---------------------------------------------------------- * 描述::商户端基础信息service类获取数据详情 *---------------------------------------------------------- *参数: *parm2:in--   String :: id  			::需要获取的id *---------------------------------------------------------- *返回： *return:out--  String :: bool   ::已经获取的数组列表 * ---------------------------------------------------------- * 日期:2017.03.03  Add by zwx ************************************************************ */
public function getInformation($id){    try{		$bool=Array();		#.获取数据基础信息		$one=$this->data->select($this->item,array("status"=>1,"id"=>$id));		 $one=count($one)==1?$one[0]:array("isCompany"=>-1);		#.获取门店基础信息		$Any=$this->model->getInformation($one['isCompany'],$id);		count($Any)>=1 && $bool=$Any[0];		return $bool;	}catch(Exception $e) {		$log=new CurrLog(1,3,$this->session->getSession("Merchant","loginName"),$this->system->getSystemTime("A"),"",$e->getMessage());		$log->error();	}}
/** *********************************************************** *方法::InformationService::saveInformation * ---------------------------------------------------------- * 描述::商户端基础信息service类保存数据方法 *---------------------------------------------------------- *参数: *parm1:in--    String :: id     :: 需要保存的id *parm2:in--    Array :: data  ::需要保存的数据 *---------------------------------------------------------- *返回： *return:out--  Array :: bool :: 操作成功状态 * ---------------------------------------------------------- * 日期:2017.03.03  Add by zwx ************************************************************ */
public function saveInformation($id,$data){    try{		$bool=false;		$rows=$this->data->update($this->item,$id,$data);		$rows>0 && $bool=true;		return $bool;	}catch(Exception $e) {		$log=new CurrLog(1,5,$this->session->getSession("Merchant","loginName"),$this->system->getSystemTime("A"),"",$e->getMessage());		$log->error();	}}
/**************************************************************方法::InformationService::checkInformation* ----------------------------------------------------------* 描述::商户端基础信息service类检测名称或者记录的状态*----------------------------------------------------------*参数:*parm1:in--    String :: id        :: 需要获取的id*parm2:in--    String :: name  ::需要验证的名称*----------------------------------------------------------*返回：*return:out--  Array :: bool :: 验证状态* ----------------------------------------------------------* 日期:2017.03.03  Add by zwx*************************************************************/
public function checkInformation($name=NULL,$id=NULL){    try{		$bool=false;		(!empty($name) && $where=array("status"=>1,"name"=>$name)) ||		(!empty($id) && $where=array("status"=>1,"id"=>$id));		$rows=$this->data->select($this->item,$where);		(!empty($rows) && count($rows)>0) && $bool=true;		return $bool;	}catch(Exception $e) {		$log=new CurrLog(1,3,$this->session->getSession("Merchant","loginName"),$this->system->getSystemTime("A"),"",$e->getMessage());		$log->error();	}}
}