<?php	/*****************************************************	 **作者：张文晓	**创始时间：2017-04-12	**描述：模块查询service类。	*****************************************************/
require_once (dirname(dirname(dirname(__FILE__)))."/libraries/Includes.php");	class ModelsService{		#.引用属性，每个控制器都需要有		private $includes;		private $data;		private $model;		private $system;		private $session;
/**	 ***********************************************************	 *方法::ModelsService::__construct	 * ----------------------------------------------------------	 *描述::模块查询service类初始化方法	 *----------------------------------------------------------	 *参数:	 *parm1:in--    无	 *----------------------------------------------------------	 *返回：	 *return:out--  无	 * ----------------------------------------------------------	 * 日期:2017.04.12  Add by zwx	 ************************************************************	 */
public function __construct(){		$this->includes=new Includes(__FILE__);		$this->includes->models("DataBase","global");		$this->includes->models("AnastoreModel");		$this->includes->libraries("CurrSystem");		$this->includes->libraries("CurrLog");		$this->includes->libraries("CurrSession");		$this->session=new CurrSession();		$this->system=new CurrSystem();		$this->model=new AnastoreModel();		$this->data=new DataBase();	}
	/**	 ***********************************************************	 *方法::ModelsService::getList	 * ----------------------------------------------------------	 * 描述::模块查询service类获取列表方法	 *----------------------------------------------------------	 *参数:	 *parm1:in--    无	 *----------------------------------------------------------	 *返回：	 *return:out--  Array :: bool :: 返回数据列表	 * ----------------------------------------------------------	 * 日期:2017.04.12  Add by zwx	 ************************************************************	 */
	public function getModelList(){			try{				$bool=Array();				$list=$this->data->select(27,array("status"=>1));				(!empty($list) && count($list)>0) && $bool=$list;				return $bool;			}catch(Exception $e) {				$log=new CurrLog(1,3,$this->session->getSession("Merchant","loginName"),$this->system->getSystemTime("A"),"",$e->getMessage());				$log->error();			}
	}
	/**	***********************************************************	*方法::ModelsService::getTotal	* ----------------------------------------------------------	*描述::获取所有记录行数	*----------------------------------------------------------	*参数:	*parm1:in--    无	*----------------------------------------------------------	*返回：	*return:out--  无	* ----------------------------------------------------------	*日期:2017.04.12  Add by zwx	************************************************************	*/
	public function getModels($modelid){			try{				$rows=$this->model->getModels($modelid);				return  count($rows)>0?$rows:Array();			}catch(Exception $e) {				$log=new CurrLog(1,3,$this->session->getSession("Merchant","loginName"),$this->system->getSystemTime("A"),"",$e->getMessage());				$log->error();			}	}
}