<?php /***************************************************** **作者：张文晓	**创始时间：2017-03-03	**描述：商户端基础信息控制器类	*****************************************************/
header("Content-type: text/html; charset=utf-8");
require_once (dirname(dirname(dirname(__FILE__)))."/libraries/Includes.php");
class Information extends CI_Controller {	
	#.引用属性，每个控制器都需要有	
	private $includes;		private $session;	private $system;	private $service;
	/**		 ***********************************************************		 *方法::Information::__construct	 * ----------------------------------------------------------		 *描述::商户端基础信息初始化方法	 *----------------------------------------------------------	;	 *参数:	 	 *parm2:in--    无	 	 *----------------------------------------------------------		 	 *返回：	 	 *return:out--  无	 	 * ----------------------------------------------------------		 	 *日期:2017.03.03  Add by zwx		 	 ************************************************************			 */
	public function __construct(){ 			parent::__construct(); 		$this->includes=new Includes(__FILE__); 		$this->includes->libraries("CurrSystem"); 		$this->includes->libraries("CurrLog"); 		$this->includes->libraries("CurrPage"); 		$this->includes->services("InformationService"); 		$this->includes->libraries("CurrSession");	    $this->session=new CurrSession();		$this->system=new CurrSystem;		$this->service=new InformationService();		$this->load->helper("url"); 	}
	/**		***********************************************************	*方法::Information::index 	* ---------------------------------------------------------- 	*描述::商户端基础信息列表主页	*----------------------------------------------------------	*参数:	*parm2:in--    无	*----------------------------------------------------------	*返回：	*return:out--  无	* ----------------------------------------------------------	*日期:2017.03.03  Add by zwx		 	************************************************************	*/
	public function index(){ 		$this->session->checkSession('Merchant');	    $data['one']=$this->service->getInformation($this->session->getSession("Merchant","providerId"));	    $log=new CurrLog(3,3,$this->session->getSession("Merchant","loginName"),$this->system->getSystemTime("A"),"商户端基础信息","",13,NULL);
	    $log->write();		($data['one']['isCompany']==1 && $this->load->view("merchant/Merchant.html",$data)) || 		($data['one']['isCompany']==0 && $this->load->view("merchant/Group.html",$data))       || 		($data['one']['isCompany']==3 && $this->load->view("merchant/Brand.html",$data)) ;	}
	/**	 ***********************************************************	 *方法::Information::updated	 * ----------------------------------------------------------	 *描述::商户端基础信息修改数据方法	 *----------------------------------------------------------	 *参数:	 *parm2:in--    无	 *----------------------------------------------------------	 *返回：	 *return:out--  无	 * ----------------------------------------------------------	 *日期:2017.03.03  Add by zwx	 ************************************************************	 */
	public function updated(){ 		$this->session->checkSession('Merchant');		$data=$_POST;		$mess=$this->system->remind();		if($this->service->checkInformation(NULL,$data['id'])){			$data['serviceDescription']=implode(';',$data['serviceDescription']);			$data['operatorName']=$this->session->getSession('Merchant','loginName');			$data['operationTime']=$this->system->getSystemTime('A');			$this->service->saveInformation($data['id'],$data) && $mess=$this->system->remind(1,'merchant/Information/index');		}else{			$mess=$this->system->remind(4);		}		$this->load->view('admin/message.html',$mess);	}
}