<?php /***************************************************** **作者：张文晓	**创始时间：2017-02-28	**描述：商户端系统消息控制器类	*****************************************************/
header("Content-type: text/html; charset=utf-8");
require_once (dirname(dirname(dirname(__FILE__)))."/libraries/Includes.php");
class Messages extends CI_Controller {	
#.引用属性，每个控制器都需要有	
private $includes;	private $session;private $system;private $service;
/**	 ***********************************************************	 *方法::Messages::__construct * ----------------------------------------------------------	 *描述::商户端系统消息初始化方法 *----------------------------------------------------------	; *参数:	  *parm2:in--    无	  *----------------------------------------------------------		  *返回：	  *return:out--  无	  * ----------------------------------------------------------		  *日期:2017.02.28  Add by zwx		  ************************************************************		 */
public function __construct(){ 		parent::__construct(); 	$this->includes=new Includes(__FILE__); 	$this->includes->libraries("CurrSystem"); 	$this->includes->libraries("CurrLog"); 	$this->includes->libraries("CurrPage"); 	$this->includes->services("MessagesService"); 	$this->includes->libraries("CurrSession");    $this->session=new CurrSession();	$this->system=new CurrSystem;	$this->service=new MessagesService();	$this->load->helper("url"); }
/**	************************************************************方法::Messages::index * ---------------------------------------------------------- *描述::商户端系统消息列表主页*----------------------------------------------------------*参数:*parm2:in--    无*----------------------------------------------------------*返回：*return:out--  无* ----------------------------------------------------------*日期:2017.02.28  Add by zwx		 *************************************************************/
public function index(){ 	$this->session->checkSession('Merchant');	$find=empty($_GET["p"])?1:$_GET["p"];	$page=new CurrPage($_SERVER["PHP_SELF"],$this->service->getTotal(),20,$find);	$data["page"]=$page->showPage();	$data["list"]=$this->service->getList($find);	$log=new CurrLog(3,3,$this->session->getSession('Merchant',"loginName"),$this->system->getSystemTime("A"),"商户端系统消息","",7,NULL);    $log->write();	$this->load->view("merchant/MessagesList.html",$data);}
/** ************************************************************方法::Messages::update* ----------------------------------------------------------*描述::商户端系统消息修改页面*----------------------------------------------------------*参数:*parm2:in--    无*----------------------------------------------------------*返回：*return:out--  无* ----------------------------------------------------------*日期:2017.02.28  Add by zwx *************************************************************/
public function update(){ 	$this->session->checkSession('Merchant');	$one=$this->service->getMessages($_GET["id"]);	$data['one']=count($one)>0?$one[0]:Array();	$log=new CurrLog(3,3,$this->session->getSession('Merchant',"loginName"),$this->system->getSystemTime("A"),"商户端系统消息","",7,$_GET["id"]);    $log->write();	$this->load->view("merchant/MessagesUpdate.html",$data);}
/**************************************************************方法::Messages::search* ----------------------------------------------------------*描述::商户端系统消息搜索方法*----------------------------------------------------------*参数:*parm2:in--    无*----------------------------------------------------------*返回：*return:out--  无* ----------------------------------------------------------*日期:2017.02.28  Add by zwx*************************************************************/
public function search(){ 	$this->session->checkSession('Merchant');	!empty($_POST) && $this->session->setSession($_POST,'messageSearch');	$session=$this->session->getSession('messageSearch');	$find=empty($_GET['p'])?1:$_GET['p'];	$page=new CurrPage($_SERVER["PHP_SELF"],$this->service->getSearchTotal($session['types'],$session['mark'],$session['startPublicDate'],$session['lastPublicDate'],$session['startPushDate'],$session['lastPushDate']),20,$find);	$data["page"]=$page->showPage();	$data["list"]=$this->service->search($session['types'],$session['mark'],$session['startPublicDate'],$session['lastPublicDate'],$session['startPushDate'],$session['lastPushDate'],$find);	$log=new CurrLog(3,3,$this->session->getSession('Merchant',"loginName"),$this->system->getSystemTime("A"),"商户端系统消息","",7,NULL);    $log->write();	$this->load->view("merchant/MessagesList.html",$data);}
/**************************************************************方法::Messages::check* ----------------------------------------------------------*描述::检测记录状态接口*----------------------------------------------------------*参数:*parm2:in--    无*----------------------------------------------------------*返回：*return:out--  无* ----------------------------------------------------------*日期:2017.02.28  Add by zwx*************************************************************/
public function check(){	$this->session->checkSession('Merchant');	header("Access-Control-Allow-Origin: *");	echo $this->service->checkMessages(NULL,$_GET["id"]) ? 4000:4004;}
}