<?php 	/***************************************************** 	**作者：张文晓		**创始时间：2017-04-12		**描述：样本查询控制器类		*****************************************************/
header("Content-type: text/html; charset=utf-8");
require_once (dirname(dirname(dirname(__FILE__)))."/libraries/Includes.php");
class Record extends CI_Controller {	
#.引用属性，每个控制器都需要有	
		private $includes;			private $session;		private $system;		private $service;
	/**			 ***********************************************************			 *方法::Record::__construct		 * ----------------------------------------------------------			 *描述::样本查询初始化方法		 *----------------------------------------------------------	;		 *参数:	 		 *parm2:in--    无	 		 *----------------------------------------------------------		 		 *返回：	 		 *return:out--  无	 		 * ----------------------------------------------------------		 		 *日期:2017.04.12  Add by zwx		 		 ************************************************************				 */
	public function __construct(){ 				parent::__construct(); 			$this->includes=new Includes(__FILE__); 			$this->includes->libraries("CurrSystem"); 			$this->includes->libraries("CurrLog"); 			$this->includes->libraries("CurrPage"); 			$this->includes->services("RecordService"); 			$this->includes->services("ModelsService");			$this->includes->services("InformationService");			$this->includes->libraries("CurrSession");			$this->session=new CurrSession();			$this->system=new CurrSystem;			$this->service=new RecordService();			$this->load->helper("url"); 		}
	/**			***********************************************************		*方法::Record::index 		* ---------------------------------------------------------- 		*描述::样本查询列表主页		*----------------------------------------------------------		*参数:		*parm2:in--    无		*----------------------------------------------------------		*返回：		*return:out--  无		* ----------------------------------------------------------		*日期:2017.04.12  Add by zwx		 		************************************************************		*/
	public function index(){ 		$find=empty($_GET["p"])?1:$_GET["p"];		$service=new InformationService();		$model=new ModelsService();		$data['model']=$model->getModels($_SESSION['modelid']);		$one=$service->getInformation($this->session->getSession("Merchant","providerId"));		$data['questionnaireId'] =empty($_POST['questionnaireId'])?$data['model'][0]['id']:$_POST['questionnaireId'];		$data['providerId']		  =empty($_POST['providerId'])?0:$_POST['providerId'];		$data['groupId']		      =empty($_POST['groupId'])?0:$_POST['groupId'];		$data['brandId']              =empty($_POST['brandId'])?0:$_POST['brandId'];		$data['areaId']                 =empty($_POST['areaId'])?0:$_POST['areaId'];		$data['startTime']           =empty($_POST['startTime'])?NULL:$_POST['startTime'];		$data['endTime']            =empty($_POST['startTime'])?NULL:$_POST['endTime'];		$one['isCompany']==3 && $page=new CurrPage($_SERVER["PHP_SELF"],$this->service->getTotal($data['questionnaireId'],$data['providerId'],$data['groupId'],$one['brandId1'],$data['areaId'],$data['startTime'],$data['endTime']),100,$find);		$one['isCompany']==1 && $page=new CurrPage($_SERVER["PHP_SELF"],$this->service->getTotal($data['questionnaireId'],$one['id'],$data['groupId'],$data['brandId'],$data['areaId'],$data['startTime'],$data['endTime']),100,$find);		$one['isCompany']==0 && $page=new CurrPage($_SERVER["PHP_SELF"],$this->service->getTotal($data['questionnaireId'],$data['providerId'],$one['id'],$data['brandId'],$data['areaId'],$data['startTime'],$data['endTime']),100,$find);		$data["page"]=$page->showPage();		$one['isCompany']==3 && $data["list"]=$this->service->getList($data['questionnaireId'],$data['providerId'],$data['groupId'],$one['brandId1'],$data['areaId'],$data['startTime'],$data['endTime'],$find);		$one['isCompany']==1 && $data["list"]=$this->service->getList($data['questionnaireId'],$one['id'],$data['groupId'],$data['brandId'],$data['areaId'],$data['startTime'],$data['endTime'],$find);		$one['isCompany']==0 && $data["list"]=$this->service->getList($data['questionnaireId'],$data['providerId'],$one['id'],$data['brandId'],$data['areaId'],$data['startTime'],$data['endTime'],$find);		$data['ques']=$this->service->getQuestions($data['questionnaireId']);		$data['iscompany']=$one['isCompany'];		$log=new CurrLog(3,3,$this->session->getSession("Merchant","loginName"),$this->system->getSystemTime("A"),"样本查询","",29,NULL);		$log->write();		$this->load->view("merchant/RecordList.html",$data);	}
}